### ISSUE TITLE
How does it look?

### ISSUE THREAD

**Issue by EwolBash** [devCU/IPS-4.4-BitTracker#1]
Curious how it looks and integrates into the forum. I appreciate the current screenshots here, but would like to know a little more. Would be willing to support you on patron as this is something I'm really interested in.

Also curious how scalable this could be? Is there any reason it couldn't handle millions of torrents? (With the right hardware)

**Comment by GaalexxC** [comment]
Will be updating these development files to a full release very shortly and will post more screens but basically have the IPS downloads layout or the classic table rows layout integrated into the IPS default style which will transform to match any theme you may be using.

As for millions of torrents the software can but can your server?

**Comment by ZooKeeper-star** [comment]
I am very interested in this, how soon will it be ready?
