### ISSUE TITLE
Donations...

### ISSUE THREAD

**Issue by ZooKeeper-star** [devCU/IPS-4.4-BitTracker#5]
There is no where to donate...How are we supposed to be able to get beta's and support, if we can not donate....

-ZooKeeper

**Comment by GaalexxC** [comment]
We will be doing beta testing in about a week or so at my site. If you would like to join the test then email me for more info. There you can also make a donation, I am not using the devcu site right now just too much on my plate and not enough time.

**Comment by ZooKeeper-star** [comment]
Yes, please send me the test site information. 
Thank you

**Comment by GaalexxC** [comment]
This is a site you may or may not have heard of but we are the oldest and most secure private sharing site ever online. We celebrate 19 years old this December so please do not mention the site outside of our community that’s how our members keep it private. Thanks

 

I need a username and valid working email (No Yahoo or Hotmail or most free insecure spam heaven accounts, Gmail, any secure email provider like Protonmail or your ISP etc.), all info is kept private and secure and never shared. I will add a temp pass which you can change after logging in.

**Comment by ZooKeeper-star** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}

**Comment by ZooKeeper-star** [comment]
I have not gotten any email with the info as of yet, just checking in...

**Comment by ZooKeeper-star** [comment]
Any udpate? Been 2 weeks since I heard anything at all...

**Comment by GaalexxC** [comment]
If you check the repo you will see 2.2.0 Final started uploading yesterday

**Comment by ZooKeeper-star** [comment]
How long until ready for use?

**Comment by ZooKeeper-star** [comment]
Are we still looking at the end of August? I am patiently waiting :)
Just want to see where your at on this, as I am very interested in this.
Thank you :)

**Comment by ZooKeeper-star** [comment]
I hope the rest of this gets updated today...Its August 31st :)

**Comment by ZooKeeper-star** [comment]
We got moved to Mid Sept, WOW!................what a huge let down!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by GaalexxC** [comment]
> There is no where to donate...How are we supposed to be able to get beta's and support, if we can not donate....
> 
> -ZooKeeper

What are you talking about? You are at the site and there are multiple ways to donate. I will send you a PM but all you need to do is either go to the sites menu under services or the member donations thread for info.
