### ISSUE TITLE
Purchase

### ISSUE THREAD

**Issue by storm2017** [devCU/IPS-4.4-BitTracker#6]
Hi, can you tell me how i can purchase this addon please, would really like to see it in action

Thanks in advance

**Comment by GaalexxC** [comment]
Its actually open source and free but not ready just yet. We will be doing beta testing in about a week or so at my site. If you would like to join the test then email me for more info.

**Comment by storm2017** [comment]
would love to join the test site, Thanks

**Comment by GaalexxC** [comment]
This is a site you may or may not have heard of but we are the oldest and most secure private sharing site ever online. We celebrate 19 years old this December so please do not mention the site outside of our community that’s how our members keep it private. Thanks

 

I need a username and valid working email (No Yahoo or Hotmail or most free insecure spam heaven accounts, Gmail, any secure email provider like Protonmail or your ISP etc.), all info is kept private and secure and never shared. I will add a temp pass which you can change after logging in.

**Comment by ZooKeeper-star** [comment]
Comment removed

**Comment by storm2017** [comment]
username = Darkmaster please and the only email i use is

**Comment by storm2017** [comment]
is there any update on this please

**Comment by ZooKeeper-star** [comment]
Any updates?

**Comment by GaalexxC** [comment]
2.2.0 Final is in the process of being added to the repo.

**Comment by ZooKeeper-star** [comment]
How long until its ready for use?Thank you Sent from Mail for Windows 10 From: Gary CornellSent: Saturday, August 29, 2020 4:30 PMTo: devCU/IPS-4.4-BitTrackerCc: ZooKeeper-star; CommentSubject: Re: [devCU/IPS-4.4-BitTracker] Purchase (#6) 2.2.0 Final is in the process of being added to the repo.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by storm2017** [comment]
when will this be fully available please?

**Comment by GaalexxC** [comment]
Please stop posting private emails here.
