### ISSUE TITLE
Something went wrong. Please try again. Error code: EX0

### ISSUE THREAD

**Issue by Serialc0de** [devCU/IPS-4.4-BitTracker#8]
`Error: Class 'IPS\bitracker\Request' not found (0)
#0 /www/wwwroot/testertracker.pw/applications/bitracker/modules/front/system/settings.php(76): IPS\bitracker\modules\front\system\_settings->_overview()
#1 /www/wwwroot/testertracker.pw/system/Dispatcher/Controller.php(101): IPS\bitracker\modules\front\system\_settings->manage()
#2 /www/wwwroot/testertracker.pw/applications/bitracker/modules/front/system/settings.php(62): IPS\Dispatcher\_Controller->execute()
#3 /www/wwwroot/testertracker.pw/system/Dispatcher/Dispatcher.php(152): IPS\bitracker\modules\front\system\_settings->execute()
#4 /www/wwwroot/testertracker.pw/index.php(13): IPS\_Dispatcher->run()
#5 {main}`

**What does this error mean?**
![1](https://user-images.githubusercontent.com/40340347/102624236-04db6200-4144-11eb-87c6-ad07c98ecad1.PNG)

**Comment by GaalexxC** [comment]
Read the ReadMe please

**_THIS IS AN INCOMPLETE DEVELOPMENT VERSION ONLY SUPPORTERS AND REQUESTS CAN ACCESS FULL VERSIONS_**
